FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    python3 \
    python3-pip \
    wget \
    bzip2 \
    libnewlib-arm-none-eabi \
    openocd \
    stlink-tools \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt
RUN wget -qO- https://developer.arm.com/-/media/Files/downloads/gnu/12.3.rel1/binrel/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi.tar.xz | tar -xJ 

ENV PATH="/opt/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin:${PATH}"

WORKDIR /project
CMD ["/bin/bash"]